# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapclientplugins\electrodeprojectionstep\qt\electrodeprojectionwidget.ui'
#
# Created: Thu Nov 29 12:31:02 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ElectrodeProjectionWidget(object):
    def setupUi(self, ElectrodeProjectionWidget):
        ElectrodeProjectionWidget.setObjectName("ElectrodeProjectionWidget")
        ElectrodeProjectionWidget.resize(1093, 872)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ElectrodeProjectionWidget.sizePolicy().hasHeightForWidth())
        ElectrodeProjectionWidget.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(ElectrodeProjectionWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.dockWidget = QtGui.QDockWidget(ElectrodeProjectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(353, 430))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.identifier_frame = QtGui.QFrame(self.dockWidgetContents)
        self.identifier_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.identifier_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.identifier_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.identifier_frame.setObjectName("identifier_frame")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.identifier_frame)
        self.verticalLayout_4.setContentsMargins(-1, 5, -1, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.identifier_label = QtGui.QLabel(self.identifier_frame)
        self.identifier_label.setObjectName("identifier_label")
        self.verticalLayout_4.addWidget(self.identifier_label)
        self.line = QtGui.QFrame(self.identifier_frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.verticalLayout.addWidget(self.identifier_frame)
        self.time_groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.time_groupBox.setObjectName("time_groupBox")
        self.gridLayout_4 = QtGui.QGridLayout(self.time_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timePlayStop_pushButton = QtGui.QPushButton(self.time_groupBox)
        self.timePlayStop_pushButton.setObjectName("timePlayStop_pushButton")
        self.gridLayout_4.addWidget(self.timePlayStop_pushButton, 1, 1, 1, 1)
        self.timeValue_label = QtGui.QLabel(self.time_groupBox)
        self.timeValue_label.setObjectName("timeValue_label")
        self.gridLayout_4.addWidget(self.timeValue_label, 0, 0, 1, 1)
        self.timeValue_doubleSpinBox = QtGui.QDoubleSpinBox(self.time_groupBox)
        self.timeValue_doubleSpinBox.setMaximum(12000.0)
        self.timeValue_doubleSpinBox.setObjectName("timeValue_doubleSpinBox")
        self.gridLayout_4.addWidget(self.timeValue_doubleSpinBox, 0, 1, 1, 1)
        self.timeLoop_checkBox = QtGui.QCheckBox(self.time_groupBox)
        self.timeLoop_checkBox.setObjectName("timeLoop_checkBox")
        self.gridLayout_4.addWidget(self.timeLoop_checkBox, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.time_groupBox)
        self.projection_groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.projection_groupBox.setObjectName("projection_groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.projection_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.projectElectrodes_label = QtGui.QLabel(self.projection_groupBox)
        self.projectElectrodes_label.setObjectName("projectElectrodes_label")
        self.gridLayout_3.addWidget(self.projectElectrodes_label, 3, 0, 1, 1)
        self.projectElectrodes_pushButton = QtGui.QPushButton(self.projection_groupBox)
        self.projectElectrodes_pushButton.setObjectName("projectElectrodes_pushButton")
        self.gridLayout_3.addWidget(self.projectElectrodes_pushButton, 3, 2, 1, 1)
        self.projectionDepth_spinBox = QtGui.QSpinBox(self.projection_groupBox)
        self.projectionDepth_spinBox.setMaximum(9999)
        self.projectionDepth_spinBox.setObjectName("projectionDepth_spinBox")
        self.gridLayout_3.addWidget(self.projectionDepth_spinBox, 1, 2, 1, 1)
        self.projectionDepth_label = QtGui.QLabel(self.projection_groupBox)
        self.projectionDepth_label.setObjectName("projectionDepth_label")
        self.gridLayout_3.addWidget(self.projectionDepth_label, 1, 0, 1, 1)
        self.projectionPointScale_label = QtGui.QLabel(self.projection_groupBox)
        self.projectionPointScale_label.setObjectName("projectionPointScale_label")
        self.gridLayout_3.addWidget(self.projectionPointScale_label, 2, 0, 1, 1)
        self.projectionPointScale_doubleSpinBox = QtGui.QDoubleSpinBox(self.projection_groupBox)
        self.projectionPointScale_doubleSpinBox.setMinimum(-99.99)
        self.projectionPointScale_doubleSpinBox.setSingleStep(0.1)
        self.projectionPointScale_doubleSpinBox.setObjectName("projectionPointScale_doubleSpinBox")
        self.gridLayout_3.addWidget(self.projectionPointScale_doubleSpinBox, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.projection_groupBox)
        spacerItem = QtGui.QSpacerItem(20, 557, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewAll_button = QtGui.QPushButton(self.frame)
        self.viewAll_button.setObjectName("viewAll_button")
        self.horizontalLayout_2.addWidget(self.viewAll_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.done_button = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done_button.sizePolicy().hasHeightForWidth())
        self.done_button.setSizePolicy(sizePolicy)
        self.done_button.setObjectName("done_button")
        self.horizontalLayout_2.addWidget(self.done_button)
        self.verticalLayout.addWidget(self.frame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dockWidget, 0, 0, 1, 1)
        self.sceneviewer_widget = BaseSceneviewerWidget(ElectrodeProjectionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewer_widget.sizePolicy().hasHeightForWidth())
        self.sceneviewer_widget.setSizePolicy(sizePolicy)
        self.sceneviewer_widget.setObjectName("sceneviewer_widget")
        self.gridLayout.addWidget(self.sceneviewer_widget, 0, 1, 1, 1)

        self.retranslateUi(ElectrodeProjectionWidget)
        QtCore.QMetaObject.connectSlotsByName(ElectrodeProjectionWidget)

    def retranslateUi(self, ElectrodeProjectionWidget):
        ElectrodeProjectionWidget.setWindowTitle(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Electrode Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.identifier_label.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Identifier", None, QtGui.QApplication.UnicodeUTF8))
        self.time_groupBox.setTitle(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.timePlayStop_pushButton.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.timeValue_label.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Time value:", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLoop_checkBox.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.projection_groupBox.setTitle(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Projection:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectElectrodes_label.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Project electrodes on plane:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectElectrodes_pushButton.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Project electrodes", None, QtGui.QApplication.UnicodeUTF8))
        self.projectionDepth_label.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Projection depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.projectionPointScale_label.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Projection point scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAll_button.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.done_button.setText(QtGui.QApplication.translate("ElectrodeProjectionWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
from mapclientplugins.electrodeprojectionstep import resources_rc
